# Generated by Django 5.1.4 on 2025-01-08 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='activve',
        ),
        migrations.AddField(
            model_name='company',
            name='active',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
