# Generated by Django 5.1.4 on 2025-01-08 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourapi', '0002_remove_company_activve_company_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=10)),
                ('about', models.CharField(max_length=100)),
                ('position', models.CharField(choices=[('HR', 'Human Resource'), ('TL', 'Team Leader'), ('DEV', 'Developer'), ('QA', 'Quality Analyst'), ('PM', 'Project Manager')], max_length=100)),
                ('added_date', models.DateField(auto_now_add=True)),
                ('active', models.BooleanField(default=True, null=True)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ourapi.company')),
            ],
        ),
    ]
